export const contractAbi = [
  "function createArena(uint256 entryFee, uint256 duration, address entryToken) returns (uint256)",
  "function joinArena(uint256 arenaId) payable",
  "function joinArenaFor(uint256 arenaId, address player)",
  "function submitScore(uint256 arenaId, address player, uint256 score)",
  "function closeArena(uint256 arenaId)",
  "function finalizeArena(uint256 arenaId, address[] winners, uint256[] percentages)",
  "function claim(uint256 arenaId)",
  "function arenaCount() view returns (uint256)",
  "function getArena(uint256 arenaId) view returns (uint256 id, uint256 entryFee, uint256 totalPool, uint64 createdAt, uint64 endTime, bool closed, bool finalized, address entryToken, uint256 playerCount)",
  "function getArenaPlayers(uint256 arenaId) view returns (address[])",
  "function getArenaWinners(uint256 arenaId) view returns (address[])",
  "function bestScores(uint256 arenaId, address player) view returns (uint256)",
  "function rewardAmounts(uint256 arenaId, address player) view returns (uint256)",
  "function claimed(uint256 arenaId, address player) view returns (bool)",
  "event ArenaCreated(uint256 indexed arenaId, uint256 entryFee, uint256 duration, uint256 endTime)",
  "event RewardPaid(uint256 indexed arenaId, address indexed player, uint256 amount)",
  "event RewardStored(uint256 indexed arenaId, address indexed player, uint256 amount)",
  "error OnlyOperator()",
  "error ArenaMissing()",
  "error ArenaClosedAlready()",
  "error ArenaStillOpen()",
  "error ArenaNotClosed()",
  "error ArenaAlreadyFinalized()",
  "error InvalidPercentageSplit()",
  "error AlreadyJoined()",
  "error WrongEntryFee()",
  "error NothingToClaim()",
  "error TokenTransferFailed()",
  "error InvalidJoinMethod()"
] as const;
