/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgenticCompetitionEngine {
  export type TransferAuthorizationStruct = {
    from: AddressLike;
    to: AddressLike;
    value: BigNumberish;
    validAfter: BigNumberish;
    validBefore: BigNumberish;
    nonce: BytesLike;
  };

  export type TransferAuthorizationStructOutput = [
    from: string,
    to: string,
    value: bigint,
    validAfter: bigint,
    validBefore: bigint,
    nonce: string
  ] & {
    from: string;
    to: string;
    value: bigint;
    validAfter: bigint;
    validBefore: bigint;
    nonce: string;
  };
}

export interface AgenticCompetitionEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "arenaCount"
      | "authorizationUsed"
      | "bestScores"
      | "claim"
      | "claimed"
      | "closeArena"
      | "createArena"
      | "finalizeArena"
      | "getArena"
      | "getArenaPlayers"
      | "getArenaWinners"
      | "hasJoined"
      | "joinArena"
      | "joinArenaFor"
      | "joinArenaWithAuthorization"
      | "operator"
      | "payWinnerWithAuthorization"
      | "rewardAmounts"
      | "submitScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArenaClosed"
      | "ArenaCreated"
      | "ArenaFinalized"
      | "ArenaJoined"
      | "ArenaJoinedWithAuthorization"
      | "AuthorizationConsumed"
      | "RewardClaimed"
      | "RewardPaid"
      | "RewardStored"
      | "ScoreSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "arenaCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizationUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bestScores",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeArena",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createArena",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeArena",
    values: [BigNumberish, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getArena",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArenaPlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArenaWinners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasJoined",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinArena",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinArenaFor",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinArenaWithAuthorization",
    values: [
      BigNumberish,
      AgenticCompetitionEngine.TransferAuthorizationStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payWinnerWithAuthorization",
    values: [
      BigNumberish,
      AddressLike,
      AgenticCompetitionEngine.TransferAuthorizationStruct,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardAmounts",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "arenaCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizationUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bestScores", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeArena", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createArena",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeArena",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getArena", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getArenaPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArenaWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasJoined", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinArena", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinArenaFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "joinArenaWithAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payWinnerWithAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
}

export namespace ArenaClosedEvent {
  export type InputTuple = [arenaId: BigNumberish];
  export type OutputTuple = [arenaId: bigint];
  export interface OutputObject {
    arenaId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArenaCreatedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    entryFee: BigNumberish,
    duration: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    arenaId: bigint,
    entryFee: bigint,
    duration: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    arenaId: bigint;
    entryFee: bigint;
    duration: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArenaFinalizedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    winners: AddressLike[],
    percentages: BigNumberish[]
  ];
  export type OutputTuple = [
    arenaId: bigint,
    winners: string[],
    percentages: bigint[]
  ];
  export interface OutputObject {
    arenaId: bigint;
    winners: string[];
    percentages: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArenaJoinedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    player: AddressLike,
    totalPool: BigNumberish
  ];
  export type OutputTuple = [
    arenaId: bigint,
    player: string,
    totalPool: bigint
  ];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
    totalPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ArenaJoinedWithAuthorizationEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    player: AddressLike,
    nonce: BytesLike,
    totalPool: BigNumberish
  ];
  export type OutputTuple = [
    arenaId: bigint,
    player: string,
    nonce: string,
    totalPool: bigint
  ];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
    nonce: string;
    totalPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuthorizationConsumedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    sponsor: AddressLike,
    recipient: AddressLike,
    nonce: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    arenaId: bigint,
    sponsor: string,
    recipient: string,
    nonce: string,
    amount: bigint
  ];
  export interface OutputObject {
    arenaId: bigint;
    sponsor: string;
    recipient: string;
    nonce: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [arenaId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardPaidEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [arenaId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardStoredEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [arenaId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    arenaId: BigNumberish,
    player: AddressLike,
    score: BigNumberish
  ];
  export type OutputTuple = [arenaId: bigint, player: string, score: bigint];
  export interface OutputObject {
    arenaId: bigint;
    player: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgenticCompetitionEngine extends BaseContract {
  connect(runner?: ContractRunner | null): AgenticCompetitionEngine;
  waitForDeployment(): Promise<this>;

  interface: AgenticCompetitionEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  arenaCount: TypedContractMethod<[], [bigint], "view">;

  authorizationUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  bestScores: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  claim: TypedContractMethod<[arenaId: BigNumberish], [void], "nonpayable">;

  claimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  closeArena: TypedContractMethod<
    [arenaId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createArena: TypedContractMethod<
    [entryFee: BigNumberish, duration: BigNumberish, entryToken: AddressLike],
    [bigint],
    "nonpayable"
  >;

  finalizeArena: TypedContractMethod<
    [
      arenaId: BigNumberish,
      winners: AddressLike[],
      percentages: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getArena: TypedContractMethod<
    [arenaId: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        id: bigint;
        entryFee: bigint;
        totalPool: bigint;
        createdAt: bigint;
        endTime: bigint;
        closed: boolean;
        finalized: boolean;
        entryToken: string;
        playerCount: bigint;
      }
    ],
    "view"
  >;

  getArenaPlayers: TypedContractMethod<
    [arenaId: BigNumberish],
    [string[]],
    "view"
  >;

  getArenaWinners: TypedContractMethod<
    [arenaId: BigNumberish],
    [string[]],
    "view"
  >;

  hasJoined: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  joinArena: TypedContractMethod<[arenaId: BigNumberish], [void], "payable">;

  joinArenaFor: TypedContractMethod<
    [arenaId: BigNumberish, player: AddressLike],
    [void],
    "nonpayable"
  >;

  joinArenaWithAuthorization: TypedContractMethod<
    [
      arenaId: BigNumberish,
      authorization: AgenticCompetitionEngine.TransferAuthorizationStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  payWinnerWithAuthorization: TypedContractMethod<
    [
      arenaId: BigNumberish,
      winner: AddressLike,
      authorization: AgenticCompetitionEngine.TransferAuthorizationStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  rewardAmounts: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  submitScore: TypedContractMethod<
    [arenaId: BigNumberish, player: AddressLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "arenaCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizationUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "bestScores"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[arenaId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeArena"
  ): TypedContractMethod<[arenaId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createArena"
  ): TypedContractMethod<
    [entryFee: BigNumberish, duration: BigNumberish, entryToken: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeArena"
  ): TypedContractMethod<
    [
      arenaId: BigNumberish,
      winners: AddressLike[],
      percentages: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getArena"
  ): TypedContractMethod<
    [arenaId: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        bigint
      ] & {
        id: bigint;
        entryFee: bigint;
        totalPool: bigint;
        createdAt: bigint;
        endTime: bigint;
        closed: boolean;
        finalized: boolean;
        entryToken: string;
        playerCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getArenaPlayers"
  ): TypedContractMethod<[arenaId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getArenaWinners"
  ): TypedContractMethod<[arenaId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasJoined"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinArena"
  ): TypedContractMethod<[arenaId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "joinArenaFor"
  ): TypedContractMethod<
    [arenaId: BigNumberish, player: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "joinArenaWithAuthorization"
  ): TypedContractMethod<
    [
      arenaId: BigNumberish,
      authorization: AgenticCompetitionEngine.TransferAuthorizationStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payWinnerWithAuthorization"
  ): TypedContractMethod<
    [
      arenaId: BigNumberish,
      winner: AddressLike,
      authorization: AgenticCompetitionEngine.TransferAuthorizationStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardAmounts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [arenaId: BigNumberish, player: AddressLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ArenaClosed"
  ): TypedContractEvent<
    ArenaClosedEvent.InputTuple,
    ArenaClosedEvent.OutputTuple,
    ArenaClosedEvent.OutputObject
  >;
  getEvent(
    key: "ArenaCreated"
  ): TypedContractEvent<
    ArenaCreatedEvent.InputTuple,
    ArenaCreatedEvent.OutputTuple,
    ArenaCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ArenaFinalized"
  ): TypedContractEvent<
    ArenaFinalizedEvent.InputTuple,
    ArenaFinalizedEvent.OutputTuple,
    ArenaFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ArenaJoined"
  ): TypedContractEvent<
    ArenaJoinedEvent.InputTuple,
    ArenaJoinedEvent.OutputTuple,
    ArenaJoinedEvent.OutputObject
  >;
  getEvent(
    key: "ArenaJoinedWithAuthorization"
  ): TypedContractEvent<
    ArenaJoinedWithAuthorizationEvent.InputTuple,
    ArenaJoinedWithAuthorizationEvent.OutputTuple,
    ArenaJoinedWithAuthorizationEvent.OutputObject
  >;
  getEvent(
    key: "AuthorizationConsumed"
  ): TypedContractEvent<
    AuthorizationConsumedEvent.InputTuple,
    AuthorizationConsumedEvent.OutputTuple,
    AuthorizationConsumedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardPaid"
  ): TypedContractEvent<
    RewardPaidEvent.InputTuple,
    RewardPaidEvent.OutputTuple,
    RewardPaidEvent.OutputObject
  >;
  getEvent(
    key: "RewardStored"
  ): TypedContractEvent<
    RewardStoredEvent.InputTuple,
    RewardStoredEvent.OutputTuple,
    RewardStoredEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;

  filters: {
    "ArenaClosed(uint256)": TypedContractEvent<
      ArenaClosedEvent.InputTuple,
      ArenaClosedEvent.OutputTuple,
      ArenaClosedEvent.OutputObject
    >;
    ArenaClosed: TypedContractEvent<
      ArenaClosedEvent.InputTuple,
      ArenaClosedEvent.OutputTuple,
      ArenaClosedEvent.OutputObject
    >;

    "ArenaCreated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      ArenaCreatedEvent.InputTuple,
      ArenaCreatedEvent.OutputTuple,
      ArenaCreatedEvent.OutputObject
    >;
    ArenaCreated: TypedContractEvent<
      ArenaCreatedEvent.InputTuple,
      ArenaCreatedEvent.OutputTuple,
      ArenaCreatedEvent.OutputObject
    >;

    "ArenaFinalized(uint256,address[],uint256[])": TypedContractEvent<
      ArenaFinalizedEvent.InputTuple,
      ArenaFinalizedEvent.OutputTuple,
      ArenaFinalizedEvent.OutputObject
    >;
    ArenaFinalized: TypedContractEvent<
      ArenaFinalizedEvent.InputTuple,
      ArenaFinalizedEvent.OutputTuple,
      ArenaFinalizedEvent.OutputObject
    >;

    "ArenaJoined(uint256,address,uint256)": TypedContractEvent<
      ArenaJoinedEvent.InputTuple,
      ArenaJoinedEvent.OutputTuple,
      ArenaJoinedEvent.OutputObject
    >;
    ArenaJoined: TypedContractEvent<
      ArenaJoinedEvent.InputTuple,
      ArenaJoinedEvent.OutputTuple,
      ArenaJoinedEvent.OutputObject
    >;

    "ArenaJoinedWithAuthorization(uint256,address,bytes32,uint256)": TypedContractEvent<
      ArenaJoinedWithAuthorizationEvent.InputTuple,
      ArenaJoinedWithAuthorizationEvent.OutputTuple,
      ArenaJoinedWithAuthorizationEvent.OutputObject
    >;
    ArenaJoinedWithAuthorization: TypedContractEvent<
      ArenaJoinedWithAuthorizationEvent.InputTuple,
      ArenaJoinedWithAuthorizationEvent.OutputTuple,
      ArenaJoinedWithAuthorizationEvent.OutputObject
    >;

    "AuthorizationConsumed(uint256,address,address,bytes32,uint256)": TypedContractEvent<
      AuthorizationConsumedEvent.InputTuple,
      AuthorizationConsumedEvent.OutputTuple,
      AuthorizationConsumedEvent.OutputObject
    >;
    AuthorizationConsumed: TypedContractEvent<
      AuthorizationConsumedEvent.InputTuple,
      AuthorizationConsumedEvent.OutputTuple,
      AuthorizationConsumedEvent.OutputObject
    >;

    "RewardClaimed(uint256,address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardPaid(uint256,address,uint256)": TypedContractEvent<
      RewardPaidEvent.InputTuple,
      RewardPaidEvent.OutputTuple,
      RewardPaidEvent.OutputObject
    >;
    RewardPaid: TypedContractEvent<
      RewardPaidEvent.InputTuple,
      RewardPaidEvent.OutputTuple,
      RewardPaidEvent.OutputObject
    >;

    "RewardStored(uint256,address,uint256)": TypedContractEvent<
      RewardStoredEvent.InputTuple,
      RewardStoredEvent.OutputTuple,
      RewardStoredEvent.OutputObject
    >;
    RewardStored: TypedContractEvent<
      RewardStoredEvent.InputTuple,
      RewardStoredEvent.OutputTuple,
      RewardStoredEvent.OutputObject
    >;

    "ScoreSubmitted(uint256,address,uint256)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
  };
}
